# Generated by Django 2.2.10 on 2020-02-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opencv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_input', models.ImageField(upload_to='images/')),
                ('file_output', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
