# Generated by Django 2.2.10 on 2020-02-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencv',
            name='file_input',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
